import { PassengerService } from "./passengerService";
import { Passenger, PassengerStatus } from "../types/passenger";

const OLD_DATA = [
  {
    sl: 1,
    name: "SHEIKH MD RUBEL",
    passportNumber: "A04683313",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "6-12-25",
    status: "Embassy Submit",
  },
  {
    sl: 2,
    name: "ISLAM NAZRUL",
    passportNumber: "A00231561",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "7-12-25",
    status: "Visa Online",
  },
  {
    sl: 3,
    name: "HANIF",
    passportNumber: "A17774255",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "6-12-25",
    status: "Processing Cancelled",
  },
  {
    sl: 4,
    name: "AHMED ALI",
    passportNumber: "A13460860",
    inOut: "IN",
    tradeName: "CRANE OPERATOR",
    agentName: "JAHANGIR ALAM",
    reference: "AHAD",
    date: "15-12-25",
    status: "Visa Online",
  },
  {
    sl: 5,
    name: "HOSEN MD SAHID",
    passportNumber: "EJ0128000",
    inOut: "IN",
    tradeName: "FORK LIFT",
    agentName: "JEBON",
    reference: "AHAD",
    date: "9-12-25",
    status: "Embassy Submit",
  },
  {
    sl: 6,
    name: "DELUAR",
    passportNumber: "A04486353",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "AZAD",
    reference: "AHAD",
    date: "7-12-25",
    status: "Embassy Submit",
  },
  {
    sl: 7,
    name: "AMIN",
    passportNumber: "A20547263",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "JEBON",
    reference: "AHAD",
    date: "9-12-25",
    status: "Embassy Submit",
  },
  {
    sl: 8,
    name: "AZAD",
    passportNumber: "A09200902",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "6-12-25",
    status: "Passport Return",
  },
  {
    sl: 9,
    name: "KAOSAR MD JIBON",
    passportNumber: "A15278435",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "6-12-25",
    status: "Embassy Submit",
  },
  {
    sl: 10,
    name: "UDDIN MD KOFIL",
    passportNumber: "A03510920",
    inOut: "IN",
    tradeName: "SECURITY GUARD",
    agentName: "JAHANGIR ALAM",
    reference: "AHAD",
    date: "11-12-25",
    status: "Visa Online",
  },
  {
    sl: 11,
    name: "ZAMAN MD SHIDUR",
    passportNumber: "A055398723",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "RONY",
    reference: "AHAD",
    date: "10-12-25",
    status: "Visa Online",
  },
  {
    sl: 12,
    name: "SALIM MD",
    passportNumber: "A19722183",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "JEBON",
    reference: "AHAD",
    date: "9-12-25",
    status: "Visa Online",
  },
  {
    sl: 13,
    name: "RAHMAN MD MEJANUR",
    passportNumber: "EL0520091",
    inOut: "IN",
    tradeName: "PLUMBER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "7-12-25",
    status: "Embassy Submit",
  },
  {
    sl: 14,
    name: "ISLAM MD BABUL",
    passportNumber: "A14472942",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "RONY",
    reference: "AHAD",
    date: "10-12-25",
    status: "Visa Online",
  },
  {
    sl: 15,
    name: "PARAN MD SHA",
    passportNumber: "A04364631",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "13-12-25",
    status: "Passport Return",
  },
  {
    sl: 16,
    name: "AHMED PARVAZ",
    passportNumber: "A12163185",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "SHA PARAN",
    reference: "SOHEL",
    date: "13-12-25",
    status: "Passport Return",
  },
  {
    sl: 17,
    name: "MD ALAMGIR",
    passportNumber: "A06780529",
    inOut: "IN",
    tradeName: "TIG WELDER",
    agentName: "MUKBUL PABNA",
    reference: "AHAD",
    date: "11-12-25",
    status: "Passport Return",
  },
  {
    sl: 18,
    name: "FAKIR RABBI",
    passportNumber: "A03145690",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "NIZ",
    reference: "AHAD",
    date: "4-12-25",
    status: "Passport Return",
  },
  {
    sl: 19,
    name: "AMIN AL",
    passportNumber: "A17267664",
    inOut: "IN",
    tradeName: "CIVIL FOREMAN",
    agentName: "JAHANGIR ALAM",
    reference: "AHAD",
    date: "15-12-25",
    status: "Visa Online",
  },
  {
    sl: 20,
    name: "SALAM MD ABDUS",
    passportNumber: "EH0796348",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "4-1-26",
    status: "Passport Return",
  },
  {
    sl: 21,
    name: "DAS TOPON",
    passportNumber: "A17598805",
    inOut: "IN",
    tradeName: "SECURITY GUARD",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "4-1-26",
    status: "Passport Return",
  },
  {
    sl: 22,
    name: "ALIM MD ABDUL",
    passportNumber: "A04330742",
    inOut: "IN",
    tradeName: "FORK LIFT",
    agentName: "NIZ",
    reference: "AHAD",
    date: "4-1-26",
    status: "Visa Online",
  },
  {
    sl: 23,
    name: "KAZI JAKIR",
    passportNumber: "A18270149",
    inOut: "IN",
    phone: "01511305398",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "4-1-26",
    status: "Visa Online",
  },
  {
    sl: 24,
    name: "RUMAN",
    passportNumber: "A21195545",
    inOut: "IN",
    tradeName: "PAINTER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "4-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 25,
    name: "Md khokon",
    passportNumber: "A21139965",
    inOut: "IN",
    phone: "01872393847",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "6-1-26",
    status: "Visa Online",
  },
  {
    sl: 26,
    name: "MIAH SADDAM",
    passportNumber: "A19150692",
    inOut: "IN",
    phone: "01985868104",
    tradeName: "GENERAL LABOUR",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "7-1-26",
    status: "Visa Online",
  },
  {
    sl: 27,
    name: "HOSSAIN MD JAKIR",
    passportNumber: "EN0281597",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "7-1-26",
    status: "Passport Return",
  },
  {
    sl: 28,
    name: "HUQ NAZMUL",
    passportNumber: "EL0600004",
    inOut: "IN",
    tradeName: "CIVIL FOREMAN",
    agentName: "NAZMUL HAQ",
    reference: "AHAD",
    date: "8-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 29,
    name: "RAHMAN MIZANUR",
    passportNumber: "A19740080",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "8-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 30,
    name: "HOSSEN JAMAL",
    passportNumber: "A13603178",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NIZ",
    reference: "AHAD",
    date: "8-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 31,
    name: "BILLAH MASUM",
    passportNumber: "A09255712",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "KANON",
    reference: "SOHEL",
    date: "10-1-26",
    status: "Visa Online",
  },
  {
    sl: 32,
    name: "MASUD MD",
    passportNumber: "A19529444",
    inOut: "IN",
    tradeName: "CARPENTER",
    agentName: "NAZMUL HAQ",
    reference: "AHAD",
    date: "14-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 33,
    name: "MOLLA NAHIAN",
    passportNumber: "A20701511",
    inOut: "IN",
    tradeName: "SAFETY OFFICER",
    agentName: "NAZMUL HAQ",
    reference: "AHAD",
    date: "14-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 34,
    name: "MIA KONOK",
    passportNumber: "A165511377",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "KANON",
    reference: "SOHEL",
    date: "10-1-26",
    status: "Visa Online",
  },
  {
    sl: 35,
    name: "ALAMIN MD",
    passportNumber: "A02056219",
    inOut: "IN",
    tradeName: "FORK LIFT",
    agentName: "KANON",
    reference: "SOHEL",
    date: "10-1-26",
    status: "Visa Online",
  },
  {
    sl: 36,
    name: "MUKHLES",
    passportNumber: "A21185985",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "KANON",
    reference: "SOHEL",
    date: "10-1-26",
    status: "Visa Online",
  },
  {
    sl: 37,
    name: "MIA MD ROBIN",
    passportNumber: "A14975761",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "KANON",
    reference: "SOHEL",
    date: "10-1-26",
    status: "Visa Online",
  },
  {
    sl: 38,
    name: "HANIF ABU",
    passportNumber: "A06754183",
    inOut: "IN",
    tradeName: "SECURITY GUARD",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "11-1-26",
    status: "Passport Return",
  },
  {
    sl: 39,
    name: "HOSEN FORIDUL",
    passportNumber: "A09472154",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "11-1-26",
    status: "Passport Return",
  },
  {
    sl: 40,
    name: "ISLAM MD SAHIDUL",
    passportNumber: "A05609291",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "14-1-26",
    status: "Visa Online",
  },
  {
    sl: 41,
    name: "KHAN TANVIR",
    passportNumber: "A21373541",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "14-1-26",
    status: "Passport Return",
  },
  {
    sl: 42,
    name: "HOSSAN MD ALAMGIR",
    passportNumber: "A12491658",
    inOut: "IN",
    tradeName: "STEEL FIXER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "13-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 43,
    name: "SHOVO",
    passportNumber: "A20538790",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "17-1-26",
    status: "Passport Return",
  },
  {
    sl: 44,
    name: "ABDUL AHAD",
    passportNumber: "A04209378",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "17-1-26",
    status: "Workpermit Issue",
  },
  {
    sl: 45,
    name: "MD ROMAN MIA",
    passportNumber: "A18738258",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "17-1-26",
    status: "Passport Return",
  },
  {
    sl: 46,
    name: "MD RAIHAN",
    passportNumber: "A01883698",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "17-1-26",
    status: "Passport Return",
  },
  {
    sl: 47,
    name: "MOHAMMAD NUR",
    passportNumber: "A07417147",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "18-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 48,
    name: "MD WALI WALLAH",
    passportNumber: "A04874970",
    inOut: "IN",
    tradeName: "ELECTRICAIN",
    agentName: "JOYNAL OFFICE",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 49,
    name: "MD SHIHAB KHAN",
    passportNumber: "A01532370",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "JOYNAL OFFICE",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 50,
    name: "MD LAL MIA",
    passportNumber: "A07972048",
    inOut: "IN",
    phone: "01316001281",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "15-1-26",
    status: "Visa Online",
  },
  {
    sl: 51,
    name: "MD MAKBUL HOSSAIN",
    passportNumber: "EN0058466",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "13-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 52,
    name: "JAHED HOSSAIN",
    passportNumber: "A05943406",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "13-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 53,
    name: "MD SHA ZAHAN",
    passportNumber: "A06980675",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 54,
    name: "MD ZEL HAQUE",
    passportNumber: "A20595199",
    inOut: "IN",
    tradeName: "STEEL FIXER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 55,
    name: "SHARIFUL ISLAM",
    passportNumber: "A18480144",
    inOut: "IN",
    tradeName: "FORK LIFT",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Passport Return",
  },
  {
    sl: 56,
    name: "LABU",
    passportNumber: "A07399566",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 57,
    name: "MD ISMAIL HOSSAIN",
    passportNumber: "A11900904",
    inOut: "IN",
    tradeName: "PAINTER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 58,
    name: "MD MOKHLESUR RAHMAN",
    passportNumber: "A05514438",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 59,
    name: "MD BORATH AKANDO",
    passportNumber: "A08152979",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 60,
    name: "SHAKIL SHEIKH",
    passportNumber: "A17333636",
    inOut: "IN",
    tradeName: "TIG WELDER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "12-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 61,
    name: "MOSTAKIN MORAD",
    passportNumber: "A09419751",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "19-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 62,
    name: "MD LIMON AHMED",
    passportNumber: "A07574357",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 63,
    name: "MD MONIRUL ISLAM",
    passportNumber: "A07358283",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "19-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 64,
    name: "NAIMUL ISLAM",
    passportNumber: "A08998374",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "19-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 65,
    name: "PARVES SHEIKH",
    passportNumber: "A13352127",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "19-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 66,
    name: "WAKID AHMED",
    passportNumber: "A08198365",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 67,
    name: "ANAMUL MIAH",
    passportNumber: "A14537305",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 68,
    name: "TAVIR AHMED",
    passportNumber: "A07262808",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 69,
    name: "RAKIB HASSAN",
    passportNumber: "A06972556",
    inOut: "IN",
    tradeName: "PLUMBER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 70,
    name: "MD SOHEL",
    passportNumber: "A05597287",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 71,
    name: "ANWAR HOSSAIN",
    passportNumber: "A05222714",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "18-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 72,
    name: "SOBUG TALUKDER",
    passportNumber: "A18790941",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "SOBUJ",
    reference: "AHAD",
    date: "20-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 73,
    name: "RUBEL MRIDHA",
    passportNumber: "A12543068",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "SOBUJ",
    reference: "AHAD",
    date: "20-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 74,
    name: "SAKIB SARDAR",
    passportNumber: "A09386381",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "SOBUJ",
    reference: "AHAD",
    date: "20-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 75,
    name: "KHAIRUL MOLLA",
    passportNumber: "A18850884",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "SOBUJ",
    reference: "AHAD",
    date: "20-1-26",
    status: "Passport Return",
  },
  {
    sl: 76,
    name: "MD AL MAMUN",
    passportNumber: "A06604913",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "21-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 77,
    name: "IAKUB MIYA",
    passportNumber: "A06148491",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "22-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 78,
    name: "MOLLA MD SERAZ",
    passportNumber: "A13059010",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "22-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 79,
    name: "MOLLA MD HASAN",
    passportNumber: "A02295520",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "22-1-26",
    status: "Passport Return",
  },
  {
    sl: 80,
    name: "MD MOSHEURE RAHMAN",
    passportNumber: "A17125025",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "KANON",
    reference: "SOHEL",
    date: "21-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 81,
    name: "SOWROV MD MEHEDI",
    passportNumber: "A08829996",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "JOYNAL OFFICE",
    reference: "SOHEL",
    date: "24-1-26",
    status: "Visa Online",
  },
  {
    sl: 82,
    name: "ISLAM MD NAZRUL",
    passportNumber: "A14953381",
    inOut: "IN",
    tradeName: "GAS CUTTING WELDER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "25-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 83,
    name: "RAHAMAN MD HABIBUIR",
    passportNumber: "A020065978",
    inOut: "IN",
    tradeName: "STEEL FIXER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "25-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 84,
    name: "MASUD MOHAMMAD",
    passportNumber: "A08365983",
    inOut: "IN",
    tradeName: "TILES MASON",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "25-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 85,
    name: "Alam MD Rahul",
    passportNumber: "A20877427",
    inOut: "IN",
    phone: "01616013154",
    tradeName: "FORK LIFT",
    agentName: "NIZ",
    reference: "AHAD",
    date: "26-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 86,
    name: "Ahmed Raju",
    passportNumber: "A09544031",
    inOut: "IN",
    phone: "01938346710",
    tradeName: "MASON",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "26-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 87,
    name: "MD Abul kalam azad",
    passportNumber: "A07118011",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "ROKON",
    reference: "AHAD",
    date: "27-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 88,
    name: "sarkar raju",
    passportNumber: "A04132826",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "27-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 89,
    name: "MD RAFIQUL ISLAM",
    passportNumber: "A11400749",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "27-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 90,
    name: "KHALIFA MINTU",
    passportNumber: "A08471558",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "27-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 91,
    name: "MD ISMAIL",
    passportNumber: "EL0479101",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "27-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 92,
    name: "SIDUL FAKIR",
    passportNumber: "EL0584248",
    inOut: "IN",
    tradeName: "ELECTRICIAN",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "27-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 93,
    name: "RAFIQUL ISLAM",
    passportNumber: "EM0352867",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "27-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 94,
    name: "MD PARVIS HASAN",
    passportNumber: "EK0495139",
    inOut: "IN",
    tradeName: "FORK LIFT",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "27-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 95,
    name: "SABJAL",
    passportNumber: "A13836687",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "SABJAL",
    reference: "AHAD",
    date: "27-1-26",
    status: "Passport Return",
  },
  {
    sl: 96,
    name: "MD SABBIR HOSEN",
    passportNumber: "A15085268",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "SABJAL",
    reference: "AHAD",
    date: "27-1-26",
    status: "Passport Return",
  },
  {
    sl: 97,
    name: "HOSSEN BELAYET",
    passportNumber: "A03136351",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "SYFUL",
    reference: "AHAD",
    date: "29-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 98,
    name: "SYFUL ISLAM",
    passportNumber: "A17232718",
    inOut: "IN",
    tradeName: "CARPENTER",
    agentName: "SYFUL",
    reference: "AHAD",
    date: "29-1-26",
    status: "Embassy Submit",
  },
  {
    sl: 99,
    name: "MOLLA BIPLAB",
    passportNumber: "A08071407",
    inOut: "IN",
    tradeName: "ELECTRIC HELPER",
    agentName: "JAMAL VAI",
    reference: "AHAD",
    date: "31-1-26",
    status: "Visa Online",
  },
  {
    sl: 100,
    name: "MD ABDAL HUSSAN",
    passportNumber: "A07999365",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "JAMAL VAI",
    reference: "AHAD",
    date: "31-1-26",
    status: "Visa Online",
  },
  {
    sl: 101,
    name: "MD MOSTOFA KAMAL",
    passportNumber: "A16120627",
    inOut: "IN",
    tradeName: "PAINTER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "29-1-26",
    status: "Processing Cancelled",
  },
  {
    sl: 102,
    name: "MD ATAUR RAHMAN",
    passportNumber: "A05949359",
    inOut: "IN",
    phone: "01819968956",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ, KHORSHED",
    reference: "AHAD",
    date: "01-02-2026",
    status: "Visa Online",
  },
  {
    sl: 103,
    name: "MD ARIFUL ISLAM",
    passportNumber: "A12982846",
    inOut: "IN",
    phone: "01568797165",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "02-02-2026",
    status: "Processing Cancelled",
  },
  {
    sl: 104,
    name: "MONJUR HASAN",
    passportNumber: "A04203722",
    inOut: "IN",
    phone: "0184366627",
    tradeName: "HEAVY DRIVER",
    agentName: "NEWTON",
    reference: "SOHEL",
    date: "02-02-2026",
    status: "Processing Cancelled",
  },
  {
    sl: 105,
    name: "JONY",
    passportNumber: "EN0229872",
    inOut: "IN",
    phone: "01614618221",
    tradeName: "CAMP CLEANER",
    agentName: "JONY",
    reference: "SOHEL",
    date: "05-02-2026",
    status: "Visa Online",
  },
  {
    sl: 106,
    name: "MD HOMUZ ALI",
    passportNumber: "A16863812",
    inOut: "IN",
    phone: "01614618221",
    tradeName: "CAMP CLEANER",
    agentName: "JONY",
    reference: "SOHEL",
    date: "05-02-2026",
    status: "Visa Online",
  },
  {
    sl: 107,
    name: "FARUK RARI",
    passportNumber: "A21532511",
    inOut: "IN",
    phone: "01327643026",
    tradeName: "HEAVY DRIVER",
    agentName: "KHOKON",
    reference: "SOHEL",
    date: "8/2/2026",
    status: "Medical Done",
  },
  {
    sl: 108,
    name: "MD AL AMIN",
    passportNumber: "A14015413",
    inOut: "IN",
    phone: "01706786401",
    tradeName: "CAMP CLEANER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 109,
    name: "SELIM PEYADA",
    passportNumber: "A20490993",
    inOut: "IN",
    phone: "01313313865",
    tradeName: "CAMP CLEANER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 110,
    name: "MD MOSTAFIZUR RAHMAN",
    passportNumber: "A19994813",
    inOut: "IN",
    phone: "01611672387",
    tradeName: "CAMP CLEANER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 111,
    name: "NUR ISLAM",
    passportNumber: "A20490920",
    inOut: "IN",
    phone: "01329390198",
    tradeName: "CAMP CLEANER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 112,
    name: "MD SIAM AHMED",
    passportNumber: "A19818676",
    inOut: "IN",
    phone: "01306662979",
    tradeName: "GENERAL LABOUR",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 113,
    name: "MD BASHIR UL ISLAM",
    passportNumber: "A20527320",
    inOut: "IN",
    phone: "01750545449",
    tradeName: "GENERAL LABOUR",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 114,
    name: "SHAHADAT HOSEN",
    passportNumber: "A21267210",
    inOut: "IN",
    phone: "01344715698",
    tradeName: "GENERAL LABOUR",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 115,
    name: "MOHOAMMAD SOHIDUL",
    passportNumber: "A17894828",
    inOut: "IN",
    phone: "01759586507",
    tradeName: "SECURITY GUARD",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 116,
    name: "MD AKTARUL ISLAM",
    passportNumber: "A20261346",
    inOut: "IN",
    phone: "01749752428",
    tradeName: "SECURITY GUARD",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 117,
    name: "ABU SAHID",
    passportNumber: "A19896616",
    inOut: "IN",
    phone: "01758355003",
    tradeName: "SECURITY GUARD",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "07-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 118,
    name: "MD HADIUL BASHAR SWRON",
    passportNumber: "A09502553",
    inOut: "IN",
    phone: "01347005859",
    tradeName: "SECURITY GUARD",
    agentName: "RIYAZ VAI",
    reference: "AHAD",
    date: "10-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 119,
    name: "MD ISMAIL KAZI",
    passportNumber: "A09800287",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "HABIB AGENT",
    reference: "SOHEL",
    date: "15-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 120,
    name: "SHAHADAT HOSSAIN SHIAD",
    passportNumber: "A1561110",
    inOut: "IN",
    tradeName: "CARPENTER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "22-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 121,
    name: "MONIRUL ISLAM",
    passportNumber: "A02171122",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "BABUL AGENT",
    reference: "SOHEL",
    date: "28-02-2026",
    status: "Embassy Submit",
  },
  {
    sl: 122,
    name: "MD IBRAHIM AZAD",
    passportNumber: "A09632585",
    inOut: "IN",
    tradeName: "CAMP CLEANER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "03-03-2026",
    status: "Passport Return",
  },
  {
    sl: 123,
    name: "JOYDEV DAS",
    passportNumber: "A19650554",
    inOut: "IN",
    tradeName: "ELECTRICIAN HELPER",
    agentName: "BASHIR ALI",
    reference: "AHAD",
    date: "04-03-2026",
    status: "Passport Return",
  },
  {
    sl: 124,
    name: "OLIUR RAHMAN",
    passportNumber: "A20228346",
    inOut: "IN",
    tradeName: "SAFETY OFFICER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "05-03-2026",
    status: "Passport Return",
  },
  {
    sl: 125,
    name: "MD ZOSHIM UDDIN",
    passportNumber: "A05041429",
    inOut: "IN",
    phone: "01830883349",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "05-03-2026",
    status: "Medical Done",
  },
  {
    sl: 126,
    name: "MD MUAS MIAH",
    passportNumber: "A06026618",
    inOut: "IN",
    phone: "01704394583",
    tradeName: "PLUMBER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "07-03-2026",
    status: "Medical Done",
  },
  {
    sl: 127,
    name: "MD ANOWAR",
    passportNumber: "A20742578",
    inOut: "IN",
    tradeName: "4G WELDER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "07-03-2026",
    status: "Embassy Submit",
  },
  {
    sl: 128,
    name: "JAHED MAHMUD RIAZ",
    passportNumber: "A19337289",
    inOut: "IN",
    phone: "01607355334",
    tradeName: "GENERAL LABOUR",
    agentName: "NIZ",
    reference: "AHAD",
    date: "09-03-2026",
    status: "Medical Done",
  },
  {
    sl: 129,
    name: "TUHIN SHAKE",
    passportNumber: "A09507637",
    inOut: "IN",
    tradeName: "FORK LIFT",
    agentName: "NIZ",
    reference: "AHAD",
    date: "08-03-2026",
    status: "Passport Return",
  },
  {
    sl: 130,
    name: "MD Ramjan Miah",
    passportNumber: "A12298162",
    inOut: "IN",
    phone: "01402997438",
    tradeName: "HEAVY DRIVER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "1/4/2026",
    status: "Medical Done",
  },
  {
    sl: 131,
    name: "MD Sujon Miah",
    passportNumber: "A21640550",
    inOut: "IN",
    phone: "01402997438",
    tradeName: "GENERAL LABOUR",
    agentName: "RAMJAN AGENT",
    reference: "SOHEL",
    date: "2/4/2026",
    status: "Medical Done",
  },
  {
    sl: 132,
    name: "Rasel Ahmed",
    passportNumber: "A07360916",
    inOut: "IN",
    phone: "01734461626",
    tradeName: "STEEL FIXER",
    agentName: "RASEL AHMED",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 133,
    name: "NOBY HOSSAIN",
    passportNumber: "A17535904",
    inOut: "IN",
    phone: "01710556190",
    tradeName: "CIVIL FOREMAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 134,
    name: "MOHAMMAD NAZRUL ISLAM",
    passportNumber: "EL03764470",
    inOut: "IN",
    phone: "01732274378",
    tradeName: "SECURITY GUARD",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 135,
    name: "ZAKIR HOSSAIN",
    passportNumber: "A15057203",
    inOut: "IN",
    phone: "01616060202",
    tradeName: "SECURITY GUARD",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 136,
    name: "SHAYKHUL ISLAM",
    passportNumber: "A19309913",
    inOut: "IN",
    phone: "01835133131",
    tradeName: "TIG WELDER",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 137,
    name: "ABUL HASAN",
    passportNumber: "A21523380",
    inOut: "COSIDER",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 138,
    name: "AMINUL ISLAM",
    passportNumber: "A02881950",
    inOut: "COSIDER",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 139,
    name: "MD RAHIM AHMED",
    passportNumber: "A01216604",
    inOut: "COSIDER",
    tradeName: "PLUMBER",
    agentName: "INSAF FLY",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 140,
    name: "MD ABDUL BAYEJID",
    passportNumber: "A11153171",
    inOut: "COSIDER",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "SOHEL",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 141,
    name: "ABDUL JALIL",
    passportNumber: "A21794158",
    inOut: "IN",
    phone: "01711399842",
    tradeName: "LIGHT DRIVER",
    agentName: "AFTAB UDDIN",
    reference: "AHAD",
    date: "8/4/2026",
    status: "Medical Done",
  },
  {
    sl: 142,
    name: "MD ANECHUR RAHMAN",
    passportNumber: "A09471031",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "NIZ R",
    reference: "AHAD",
    date: "12/4/2026",
    status: "Passport Submit",
  },
  {
    sl: 143,
    name: "MD LABLU HAQUE",
    passportNumber: "A09896062",
    inOut: "IN",
    tradeName: "MASON",
    agentName: "NIZ R",
    reference: "AHAD",
    date: "12/4/2026",
    status: "Passport Submit",
  },
  {
    sl: 144,
    name: "NORESH CHANDRA",
    passportNumber: "B00606506",
    inOut: "IN",
    phone: "01891573743",
    tradeName: "SECURITY GUARD",
    agentName: "HARON AGENT",
    reference: "SOHEL",
    date: "20/4/26",
    status: "Medical Done",
  },
  {
    sl: 145,
    name: "MD SAHADAT HOSSIN",
    passportNumber: "A04214587",
    inOut: "IN",
    phone: "01811990697",
    tradeName: "STEEL FIXER",
    agentName: "NIZ",
    reference: "AHAD",
    date: "12/04/2026",
    status: "Medical Done",
  },
  {
    sl: 146,
    name: "ANAMUL HAQU",
    passportNumber: "A22057981",
    inOut: "IN",
    phone: "01626409333",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "23/04/2026",
    status: "Medical Done",
  },
  {
    sl: 147,
    name: "MD ANISUR RAHMAN",
    passportNumber: "A09648766",
    inOut: "IN",
    phone: "01806948441",
    tradeName: "GENERAL LABOUR",
    agentName: "NIZ",
    reference: "SOHEL",
    date: "20/04/2026",
    status: "Medical Done",
  },
  {
    sl: 148,
    name: "RABBI FAKIR",
    passportNumber: "A12849176",
    inOut: "IN",
    phone: "01683086542",
    tradeName: "Painter",
    agentName: "FARUK VAI",
    reference: "AHAD",
    date: "27/04/26",
    status: "Medical Done",
  },
  {
    sl: 149,
    name: "RIAZ PHADA",
    passportNumber: "EM0699945",
    inOut: "IN",
    phone: "017490119453",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "29/04/2026",
    status: "Medical Done",
  },
  {
    sl: 150,
    name: "MD MEHEDI HASAN",
    passportNumber: "A11491546",
    inOut: "IN",
    phone: "01793632827",
    tradeName: "CAMP CLEANER",
    agentName: "NIZ",
    reference: "MINA",
    date: "29/04/2026",
    status: "Medical Done",
  },
  {
    sl: 151,
    name: "MOHIN UDDIN",
    passportNumber: "A03141779",
    inOut: "IN",
    phone: "01715203590",
    tradeName: "LIGHT DRIVER",
    agentName: "KAWSAR VAI",
    reference: "AHAD",
    date: "02/05/2026",
    status: "Medical Done",
  },
  {
    sl: 152,
    name: "JAKIR HOSSAIN",
    passportNumber: "A21077455",
    inOut: "IN",
    phone: "1712741192",
    tradeName: "MASON",
    agentName: "KAMAL AGENT",
    reference: "SOHEL",
    date: "05/05/2026",
    status: "Medical Done",
  },
  {
    sl: 153,
    name: "MD ANWAR MULLAH",
    passportNumber: "A09689232",
    inOut: "IN",
    phone: "1350995608",
    tradeName: "HEAVY DRIVER",
    agentName: "agent",
    reference: "AHAD",
    date: "04/05/2026",
    status: "Processing Cancelled",
  },
  {
    sl: 154,
    name: "MD ALAMGIR HOSSAIN",
    passportNumber: "A09734346",
    inOut: "IN",
    phone: "1350995608",
    tradeName: "ELECTRICIAN",
    agentName: "AGENT",
    reference: "AHAD",
    date: "04/05/2026",
    status: "Processing Cancelled",
  },
  {
    sl: 155,
    name: "TOWKIR AHMED MIM",
    passportNumber: "EM0439594",
    inOut: "IN",
    phone: "1862381712",
    tradeName: "SECURITY GUARD",
    agentName: "NIZ",
    reference: "MINA",
    date: "04/05/2026",
    status: "Medical Done",
  },
  {
    sl: 156,
    name: "MOHAMMAD FARUK",
    passportNumber: "A03526416",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "ARMAN",
    date: "04/05/2026",
    status: "Medical Done",
  },
  {
    sl: 157,
    name: "NURUJJAMAN",
    passportNumber: "EN0361537",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "ARMAN",
    date: "04/05/2026",
    status: "Medical Done",
  },
  {
    sl: 158,
    name: "PAYEL AHMED",
    passportNumber: "EM0341622",
    inOut: "IN",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "ARMAN",
    date: "04/05/2026",
    status: "Medical Done",
  },
  {
    sl: 159,
    name: "MD HASEM",
    passportNumber: "A05868668",
    inOut: "IN",
    tradeName: "HEAVY DRIVER",
    agentName: "INSAF FLY",
    reference: "ARMAN",
    date: "04/05/2026",
    status: "Medical Done",
  },
  {
    sl: 160,
    name: "MD SHIBLU UDDIN",
    passportNumber: "A20386120",
    inOut: "COSIDER",
    tradeName: "GENERAL LABOUR",
    agentName: "INSAF FLY",
    reference: "ARMAN",
    date: "",
    status: "Medical Done",
  },
  {
    sl: 161,
    name: "MD ABU SHAID KHAN",
    passportNumber: "A09108629",
    inOut: "COSIDER",
    phone: "019687197000",
    tradeName: "ELECTRICIAN",
    agentName: "NIZ",
    reference: "AHAD",
    date: "06/05/2026",
    status: "Medical Done",
  },
  {
    sl: 162,
    name: "MD PALASH MONDAL",
    passportNumber: "A21891365",
    inOut: "CSCES",
    phone: "01726920282",
    tradeName: "ELECTRICIAN",
    agentName: "RAKIB AGENT HEATPUR",
    reference: "ARMAN",
    date: "05/05/2026",
    status: "Medical Done",
  },
  {
    sl: 163,
    name: "LUKMAN AHMED",
    passportNumber: "A15006806",
    inOut: "CSCES",
    phone: "01870543370",
    tradeName: "CLEANER",
    agentName: "NIZ",
    reference: "MINA",
    date: "09/05/2026",
    status: "Processing Cancelled",
  },
  {
    sl: 164,
    name: "RIPON MIAH",
    passportNumber: "A21957063",
    inOut: "CSCES",
    phone: "01724839017",
    tradeName: "CLEANER",
    agentName: "NIZ",
    reference: "MINA",
    date: "10/05/2026",
    status: "Medical Done",
  },
];

export const DataSeeder = {
  async seedOldData(uid: string) {
    console.log("Seeding old data...");
    const passengers = OLD_DATA.map((item) => ({
      sl: item.sl,
      name: item.name,
      passportNumber: item.passportNumber,
      inOut:
        item.inOut?.toUpperCase() === "IN" ||
        item.inOut?.toUpperCase() === "OUT"
          ? item.inOut.toUpperCase() === "IN"
            ? "In"
            : "Out"
          : "In",
      companyName:
        item.inOut?.toUpperCase() !== "IN" &&
        item.inOut?.toUpperCase() !== "OUT"
          ? item.inOut
          : "",
      phone: item.phone || "N/A",
      tradeName: item.tradeName,
      agentName: item.agentName,
      agentNumber: "",
      reference: item.reference,
      date: item.date || new Date().toLocaleDateString(),
      status: item.status as PassengerStatus,
      country: "Unknown",
      documents: [],
      history: [
        {
          status: item.status as PassengerStatus,
          updatedBy: "System Migrator",
          updatedByUid: uid,
          timestamp: new Date().toISOString(),
        },
      ],
      createdBy: uid,
    }));

    try {
      await PassengerService.bulkAddPassengers(passengers);
      console.log("Seeding complete.");
    } catch (e) {
      console.error("Bulk seeding failed:", e);
      throw e;
    }
  },
};
